# Podfile for ImageOptim
# This adds support for modern image formats

platform :osx, '10.15'

target 'ImageOptim\' do
  use_frameworks!
  
  # WebP support
  pod 'libwebp', '~> 1.3'
  
  # Note: libavif is not available via CocoaPods
  # You'll need to build it manually or use a package manager like Homebrew
end

# Post-install hook to configure build settings
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.15'
      config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
    end
  end
end